#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lua'

def options(opt):
	return

def configure(conf):
	if conf.env.DEST_OS in ["linux", "android", "freebsd", "osx"]:
		conf.define( "LUA_USE_LINUX", 1 )
	return

def build(bld):
	source = [
		"src/lapi.c",
		"src/lauxlib.c",
		"src/lbaselib.c",
		"src/lcode.c",
		"src/ldblib.c",
		"src/ldebug.c",
		"src/ldo.c",
		"src/ldump.c",
		"src/lfunc.c",
		"src/lgc.c",
		"src/linit.c",
		"src/liolib.c",
		"src/llex.c",
		"src/lmathlib.c",
		"src/lmem.c",
		"src/loadlib.c",
		"src/lobject.c",
		"src/lopcodes.c",
		"src/loslib.c",
		"src/lparser.c",
		"src/lstate.c",
		"src/lstring.c",
		"src/lstrlib.c",
		"src/ltable.c",
		"src/ltablib.c",
		"src/ltm.c",
		"src/lundump.c",
		"src/lvm.c",
		"src/lzio.c",
		"src/print.c",
		"src/bit.c",
	]

	includes = [
		'.',
		'./src',
		'../public',
		'../common'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

