#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'client'

def options(opt):
	return

games = {
	'hl2': ['client_base.vpc', 'client_hl2.vpc'],
	'hl2mp': ['client_base.vpc', 'client_hl2mp.vpc'],
	'hl1': ['client_base.vpc', 'client_hl1.vpc'],
	'episodic': ['client_base.vpc', 'client_episodic.vpc'],
	'portal': ['client_base.vpc', 'client_portal.vpc'],
	'hl1mp': ['client_base.vpc', 'client_hl1mp.vpc'],
	'cstrike': ['client_base.vpc', 'client_cstrike.vpc'],
	'dod': ['client_base.vpc', 'client_dod.vpc'],
	'tf': [
		'client_base.vpc',
		'client_econ_base.vpc',
		'../shared/tf/tf_gcmessages_include.vpc',
		'client_tf.vpc'
	]
}

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'game_controls',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../vgui2/include',
		'../../vgui2/controls',
		'../shared'
	]

	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'RT',
		'ZLIB'
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android' and not bld.env.IOS:
		install_path += '/'+bld.env.GAMES+'/bin'

	source = [ 'in_touch.cpp' ]
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	source += game["sources"] + ['../../public/tier0/memoverride.cpp']

	# TF2 pulls in the econ / GameCoordinator layer, which is protobuf-based.
	# build-ios-deps.sh stages the headers and generates the .pb.cc sources.
	if bld.env.GAMES == 'tf':
		import os
		# Resolve against this wscript's own directory. os.path.abspath() alone
		# would resolve against waf's launch directory (the repo root) and
		# silently yield a path that does not exist, which meant the generated
		# .pb.cc sources below were never added to the build.
		here = bld.path.abspath()
		gen_dir = os.path.normpath(os.path.join(here, '..', 'shared', 'generated_proto'))
		includes += [
			os.path.normpath(os.path.join(here, '..', '..', 'thirdparty', 'protobuf', 'include')),
			gen_dir,
			'../shared/tf',
			'../shared/econ',
			'tf',
			'econ',
		]
		if os.path.isdir(gen_dir):
			# Walk, so a proto that protoc chose to emit into a subdirectory is
			# still compiled and its header still reachable.
			for _dir, _subdirs, _files in os.walk(gen_dir):
				_pb = [os.path.join(_dir, f) for f in sorted(_files) if f.endswith('.pb.cc')]
				if _pb:
					source += _pb
				if _dir != gen_dir:
					includes += [_dir]
		else:
			bld.fatal('TF2 build needs generated protobuf sources, but %s is missing. Run scripts/build-ios-deps.sh with BUILD_PROTOBUF=1.' % gen_dir)
		libs += ['PROTOBUF', 'gcsdk']
	includes += game["includes"]
	defines = game["defines"]

	defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

