#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	if bld.env.IOS:
		includes += bld.env.INCLUDES_SDL2
	defines = []
	libs = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']
	if bld.env.IOS:
		source += ['SDL_uikit_main.c', 'ios/Launchdiag.m']
		libs += ['FOUNDATION', 'UIKIT', 'OBJC', 'COREGRAPHICS', 'AVFOUNDATION', 'SDL2']
		ios_linkflags = ['-Wl,-rpath,@executable_path']

	install_path = bld.env.BINDIR
	launcher_kw = dict(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
	if bld.env.IOS:
		launcher_kw['linkflags'] = ios_linkflags
	bld(**launcher_kw)

